-- ============================================================
-- DAY 3: Customer Behaviour Analysis
-- ============================================================
-- Techniques: JOINs, subqueries, GROUP BY, HAVING, DATE functions
-- Questions: Q9, Q12, Q13, Q15, Q23
-- ============================================================
